param(
    [Parameter(Mandatory = $true)][string]$GameDirectory,
    [ValidateSet('Debug', 'Release')][string]$Configuration = 'Release',
    [string]$MSBuildPath,
    [string]$NuGetSource = (Join-Path $env:USERPROFILE '.nuget\packages'),
    [switch]$Package
)
$ErrorActionPreference = 'Stop'
$repo = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$game = [IO.Path]::GetFullPath($GameDirectory)
if (!(Test-Path -LiteralPath (Join-Path $game 'Beat Saber_Data\Managed\Main.dll'))) { throw 'Beat Saber reference DLLs were not found.' }
if (!$MSBuildPath) {
    $vswhere = Join-Path ([Environment]::GetEnvironmentVariable('ProgramFiles(x86)')) 'Microsoft Visual Studio\Installer\vswhere.exe'
    $MSBuildPath = & $vswhere -latest -products '*' -requires Microsoft.Component.MSBuild -find 'MSBuild\**\Bin\MSBuild.exe' | Select-Object -First 1
}
if (!$MSBuildPath -or !(Test-Path -LiteralPath $MSBuildPath)) { throw 'Specify MSBuildPath for a Visual Studio installation with .NET Framework 4.7.2 targeting support.' }
$packages = Join-Path $env:USERPROFILE '.nuget\packages'
$arguments = @((Join-Path $repo 'MovementRecorder\MovementRecorder.csproj'), '/restore', "/p:Configuration=$Configuration",
    "/p:BeatSaberDir=$game", "/p:GameDirectory=$game", "/p:RestoreSources=$NuGetSource", "/p:RestorePackagesPath=$packages",
    "/p:NuGetPackagesDirectory=$packages", '/p:NuGetAudit=false', '/p:DisableCopyToGame=True', '/p:DisableCopyToPlugins=True',
    '/nologo', '/verbosity:minimal')
Push-Location -LiteralPath (Join-Path $repo 'MovementRecorder')
try {
    & $MSBuildPath @arguments
    if ($LASTEXITCODE -ne 0) { throw "MSBuild failed: $LASTEXITCODE" }
} finally { Pop-Location }
$dll = Join-Path $repo "MovementRecorder\bin\$Configuration\MovementRecorder.dll"
Get-FileHash -LiteralPath $dll -Algorithm SHA256
if ($Configuration -eq 'Release') {
    $zip = @(Get-ChildItem -LiteralPath (Join-Path $repo 'MovementRecorder\bin\Release\zip') -Filter 'MovementRecorder-*.zip')
    if ($zip.Count -ne 1) { throw 'Expected one ZIP generated by Beat Saber Modding Tools.' }
    Get-FileHash -LiteralPath $zip[0].FullName -Algorithm SHA256
}
# -Package is retained for old commands; every Release build uses the project's BSMT ZIP target.
